### ISSUE TITLE
The quick start doesn't run

### ISSUE THREAD

**Issue by evan-boissonnot** [googleworkspace/browser-samples#27]
## Expected Behavior
Disconnect button appear

## Actual Behavior
Just connect button is able, even if i click to oauth connect

## JavaScript Console Output
nothing :(

(View your JavaScript Console to see if there are any errors)

## Specifications

- Browser (Chrome/Internet Explorer/Firefox):
Chrome
- OS (Mac/Linux/Windows): 
Windows

**Comment by sqrrrl** [comment]
Tried calendar quickstart w/ghostery (block all trackers enabled) and still unable to reproduce :(

**Comment by sales2655** [comment]
เบราว์เซอร์ของคุณไม่รองรับ JavaScript หรือปิดใช้ JavaScript อยู่

**Comment by fernandoeqc** [comment]
hello guys. i had the same problem after trying hard i found the error.
In cmd, when starting python -m http.server 8000, the current folder must be the root. That is, just C: \> ... I was working on C: \ Users \ fernando ...>, so it didn't work.
Giving a cd .. to the root will solve the problem. I hope it helps.
