### ISSUE TITLE
dpiframe_initialization_failed - http://freewheel has not been whitelisted for client ID ...

### ISSUE THREAD

**Issue by rweil55** [googleworkspace/browser-samples#71]
## Expected Behavior
using sample code from "Browser Quickstart"  with http://freewheel/index.html
https://developers.google.com/drive/api/v3/quickstart/js#prerequisites

no error message
(Include the sample name)

## Actual Behavior
"error": "idpiframe_initialization_failed",
  "details": "Not a valid origin for the client: http://freewheel has not been whitelisted for client ID 895878361325-0805lu8fmgtrevplaeleaealh0qqkcrk.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
## JavaScript Console Output
no errors
## Specifications

- Browser Chrome
- OS Windows

**Comment by sqrrrl** [comment]
The quickstart set up for the client ID only sets up localhost as a valid origin (even though localhost and your hostname point to the same machine, they're not exactly the same thing.). Either:

* Go to the console and add your hostname as a valid origin (might have to fully qualify it)
* Access the page at http://localhost instead.
