### ISSUE TITLE
google picker UI is not wokring

### ISSUE THREAD

**Issue by shafa909** [googleworkspace/browser-samples#99]
google picker auth is not migrated to google Identity Services library

`{ 
     error: "idpiframe_initialization_failed"
     details:"You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."
}`

<img width="1380" alt="Screenshot 2022-05-11 at 9 20 23 PM" src="https://user-images.githubusercontent.com/23289583/167983992-a6efb19b-a8ce-48d8-be46-a901de7a9dd7.png">

**Comment by martin19** [comment]
same here.. why did I expect this.

**Comment by sqrrrl** [comment]
The picker sample has been updated to use GIS.
